
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package uy.edu.ucu.jsonql2019.parser;

/** CUP generated interface containing symbol constants. */
public interface JSONQLTokens {
  /* terminals */
  public static final int LPARENT = 5;
  public static final int RPARENT = 6;
  public static final int MULT = 3;
  public static final int BSLASH = 34;
  public static final int NOT_EQUAL = 9;
  public static final int GREATER = 11;
  public static final int REGEX = 38;
  public static final int LESS = 10;
  public static final int MINUS = 18;
  public static final int NOT = 14;
  public static final int AND = 15;
  public static final int OPASIGN = 35;
  public static final int IN = 33;
  public static final int OR = 16;
  public static final int BOOL = 39;
  public static final int COMMA = 24;
  public static final int NENCA = 28;
  public static final int DIV = 4;
  public static final int LESS_EQUAL = 12;
  public static final int PLUS = 17;
  public static final int IF = 29;
  public static final int ID = 40;
  public static final int DOT = 31;
  public static final int EOF = 0;
  public static final int EQUAL = 8;
  public static final int GREATER_EQUAL = 13;
  public static final int error = 1;
  public static final int NULL = 25;
  public static final int NUMBER = 36;
  public static final int EQ = 7;
  public static final int LBRACK = 21;
  public static final int COLON = 23;
  public static final int LBRACE = 19;
  public static final int ELSE = 30;
  public static final int ENCA = 27;
  public static final int RBRACK = 22;
  public static final int LET = 32;
  public static final int RBRACE = 20;
  public static final int ENC = 26;
  public static final int ROOT = 2;
  public static final int STRING = 37;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ROOT",
  "MULT",
  "DIV",
  "LPARENT",
  "RPARENT",
  "EQ",
  "EQUAL",
  "NOT_EQUAL",
  "LESS",
  "GREATER",
  "LESS_EQUAL",
  "GREATER_EQUAL",
  "NOT",
  "AND",
  "OR",
  "PLUS",
  "MINUS",
  "LBRACE",
  "RBRACE",
  "LBRACK",
  "RBRACK",
  "COLON",
  "COMMA",
  "NULL",
  "ENC",
  "ENCA",
  "NENCA",
  "IF",
  "ELSE",
  "DOT",
  "LET",
  "IN",
  "BSLASH",
  "OPASIGN",
  "NUMBER",
  "STRING",
  "REGEX",
  "BOOL",
  "ID"
  };
}

